using System.Reflection;
using System.Resources;

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Revision
//      Build Number

[assembly: AssemblyCompany("ABB")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyVersion("99.99.0.0")]

/*****************************************************************************
 * This file is generated by MSBuild.
 *
 * DO NOT EDIT IT BY HAND and DO NOT CHECK IN CHANGES TO IT
 *
 *****************************************************************************/ 
 
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyInformationalVersion("99.99.0.0-Debug-dev")]
#else
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyInformationalVersion("99.99.0.0-Release-dev")]
#endif
