///////////////////////////////////////////////////////
//This file is generated by MSBuild.
//
//Do not edit it by hand!
//
///////////////////////////////////////////////////////

using System.Reflection;
using System.Resources;

[assembly: AssemblyCompany("ABB")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyVersion("0.0.0.0")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
